Feat/39 index carousel
roclin-grp/roclin-grp.github.io pull request #41
Opened 2017-12-16 22:22 UTC by mavstronaut

Fixed base.

Issue [#39](https://github.com/roclin-grp/roclin-grp.github.io/issues/39)

Made some minor tweaks to styling. Still has cleaning up to be done, but in working on this I think I know how I want things to look more clearly.

Obviously, the copy and everything will be focused and honed over time, but I wanted to get some content that might fit the bill to see how the pages would flow approximately.

Played around in paint to work up a logo concept that should do for now. resized it a few times but didn't change the favicons as it is a minor detail for another hour.

The images issue is still an open question, and proper configuration so that the carousel images point to the images folder and not /blog/*.png

2017-12-19 22:07 UTC, loljoho commented on index.md
>  # You don't need to edit this file, it's empty on purpose.
@mavstronaut I'm not sure if you saw this comment.

2017-12-19 22:31 UTC, loljoho requested changes
Make sure you take the necessary steps to address these issues.  Thanks :)

2017-12-19 22:31 UTC, loljoho commented on index.md
> +layout      : cover
Error on serve:
```
Build Warning: Layout 'cover' requested in index.md does not exist.
```

Also, this is how the home page loaded for me:

![image](https://user-images.githubusercontent.com/8849837/34074132-aea34422-e276-11e7-9678-1b61bec6b729.png)

Make sure you're familiar with [YAML Front Matter](https://jekyllrb.com/docs/frontmatter/).

2017-12-19 22:31 UTC, loljoho commented on _includes/layout/navigation.html
> +        <span><img src="/images/rlg-concept-61x65.png"> {{ site.title }}</span>
Error when navigating to homepage:
```
[2017-12-19 17:19:29] ERROR `/images/rlg-concept-61x65.png' not found.
```

Make sure to commit that image, even if it's not the final version.

2017-12-19 22:31 UTC, loljoho commented on _includes/layout/footer.html
> +<script>
This JS code should be located in located in the external `js/main.js` file, as per [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns).

The `_includes/body/scripts.html` partial file is responsible for loading all external scripts.

2017-12-19 22:31 UTC, loljoho commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
Make sure we discuss any use of third party services, plugins, or modules before implementing them.  I'm not familiar with TypeForm and somehow missed this when I skimmed the commits earlier.

It also renders terribly:

![image](https://user-images.githubusercontent.com/8849837/34181662-1a32f554-e4e1-11e7-85a3-59ecefea3e1a.png)

For now, a simple [Bootstrap form](https://getbootstrap.com/docs/3.3/css/#forms) will do.  Making a pretty contact form is not that high up on our list of priorities at the moment.

Lastly, this should not be an entire layout file.  Refer to the Jekyll documentation again, especially on [Front Matter](https://jekyllrb.com/docs/frontmatter/) and [Creating pages](https://jekyllrb.com/docs/pages/).

2017-12-19 22:31 UTC, loljoho commented on index.md
> +    <p><img src="/images/rlg-concept2-102x110.png" alt="roclin-logo"></p>
Error when navigating to page(s):
```
[2017-12-19 17:09:15] ERROR `/images/rlg-concept2-102x110.png' not found.
```

Also, make sure you commit the image, even if it's not the final version.

2017-12-19 22:31 UTC, loljoho commented on _pages/blog.md
> +                              <img src="carousel3.png" alt="work with us">
This should be `<img src="images/carousel3.png">` if it's located in the `images/` directory.

Also, commit these images!

2017-12-19 22:31 UTC, loljoho commented on _pages/blog.md
> +                                <img src="carousel2.png" alt="roclineage blog">
This should be `<img src="images/carousel2.png">` if it's located in the `images/` directory.

Also, commit these images!

2017-12-19 22:31 UTC, loljoho commented on _pages/blog.md
> +                                <img src="carousel1.png" alt="who we are">
This should be `<img src="images/carousel1.png">` if it's located in the `images/` directory.

Also, commit these images!

2017-12-19 22:36 UTC, loljoho commented
Oops, I messed up with the Request Review feature of GitHub which is relatively new, and with which I'm not quite familiar yet.

Make sure you look over all the comments I made, and not just the 3 or so that are part of the "requested changes", and push new commits accordingly.

Cheers :)

2017-12-19 22:39 UTC, mavstronaut commented on index.md
>  # You don't need to edit this file, it's empty on purpose.
Saw it before and thought I was putting this somewhere else when I was working. I can move it, but does it really matter in this case? 
Seems like an easy fix but I just looked and couldn't solve it in under 5 minutes so I don't know if it's worth spending time on. This company site only has to work.

2017-12-19 22:41 UTC, mavstronaut commented on _includes/layout/footer.html
> +<script>
fixed.

2017-12-19 22:44 UTC, loljoho commented on index.md
>  # You don't need to edit this file, it's empty on purpose.
See [this comment](https://github.com/roclin-grp/roclin-grp.github.io/pull/41#discussion_r157889247).

Sorry about that, all the code comments got split up.

2017-12-19 22:45 UTC, mavstronaut commented on _includes/layout/navigation.html
> +        <span><img src="/images/rlg-concept-61x65.png"> {{ site.title }}</span>
woop. thought I had, added to commit.

2017-12-19 22:48 UTC, mavstronaut commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
I am still playing around with it, but it's easy and works. 

I do want the site to be clean and will correct this, but I'm not looking to spend a thousand hours tweaking things on the company site which is just a business card. It only needs to work.

2017-12-19 22:59 UTC, mavstronaut commented on _pages/blog.md
> +                                <img src="carousel1.png" alt="who we are">
Tried this method as you describe and it did not work. Tried again and it still does not work.

2017-12-19 22:59 UTC, mavstronaut commented on _pages/blog.md
> +                                <img src="carousel2.png" alt="roclineage blog">
** same as other comment. this method did not function.

2017-12-19 22:59 UTC, loljoho commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
Right, but I'm not sure if it'll work, and adding in a third-party service will complicate things.

And part of the reason I wanted you to work on this is to help you form good practices and coding conventions, as well as learning basic HTML/CSS/JS.

The issues I have with the implementation (as it appears currently) are as follows, off the top of my head:

 - It renders *terribly* in browser and looks unprofessional.  For instance: the overflow (scrolling) is screwed up; the UI is terribly confusing; and the weird background, loading spinner, and navigation disappearing is inconsistent with the rest of the site.
 - I'm not familiar at all with this particular service.  Remember, we still need an AJAX call or *something* here to submit the form data.  
 - Keeping it simple.  Using a third party service for something that can be done with a few lines of HTML, CSS, and JS is overkill.
 - That "Create your own typeform" link in the bottom right is really annoying and ugly.
 - Last time we discussed marketing/email campaign services (e.g. MailChimp) which we would inevitably have to use.  They usually already have form builders, or APIs that are accessible via a simple AJAX call.

2017-12-19 22:59 UTC, mavstronaut commented on _pages/blog.md
> +                              <img src="carousel3.png" alt="work with us">
did not work.

2017-12-19 23:00 UTC, mavstronaut commented on index.md
> +layout      : cover
i have been familiarizing myself as I'm attempting to setup categories for the posts.. however not sure why the landing works for me and not you

2017-12-19 23:01 UTC, loljoho commented on index.md
> +layout      : cover
I was referring to the `layout` parameter of the Front Matter.

2017-12-19 23:01 UTC, mavstronaut commented on index.md
> +    <p><img src="/images/rlg-concept2-102x110.png" alt="roclin-logo"></p>
committed.

2017-12-19 23:03 UTC, loljoho commented on _pages/blog.md
> +                                <img src="carousel2.png" alt="roclineage blog">
Okay then.  Commit the images anyways, so I can take a look when you push.

2017-12-19 23:07 UTC, mavstronaut commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
The form data goes to their service and will look good once it updates. Nothing is required at this point I already tested that I get the submissions. #goodenoughfornow

I'm really not concerned until the point where we are going to start sending out emails, I want to have a working site that can be updated, as the contact form is low priority I can use the mailchimp form submission at that point in time.

Fixing up the copy will be the fun part after these elements are displaying properly.

2017-12-19 23:10 UTC, loljoho commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
For example: https://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

Adding an additional service *just* for forms seems like overkill to me.

2017-12-20 03:48 UTC, mavstronaut commented on _layouts/contact.html
> + <div class="typeform-widget" data-url="https://mavrickbarona.typeform.com/to/Uj7res" data-transparency="50" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 100%;" > </div> <
it'd make sense talking on it in conversation. features need to be operational now. they can be reworked again later as things are done over. 
i very much want to get both of us focused on the tagmap visualization and work on the company page as i'm writing posts and our marketing / branding / product come together.

2017-12-20 17:38 UTC, loljoho commented
I only see one new commit `1b09a26`.  Are you still working on this?

2018-01-30 21:11 UTC, merged

2018-01-30 21:11 UTC, loljoho commented
Eschewing strict and proper workflow to get this finished.

Closes: #39